### ISSUE TITLE
Returning from Debugger Perspective resets the Default

### ISSUE THREAD

**Issue by rtyler** [AdaCore/gps#40] opened 2018-11-19 19:58 UTC
**Steps to reproduce**

1. Open a project in the Default Perspective.
1. Add an "OS Shell" window
1. Click "Build and Debug" which switches into the Debugger perspective
1. Click "Terminate Debugger"

The IDE is then returned to a completely reset Default Perspective with the OS Shell window gone.

**Expected:**

According to [this documentation](http://docs.adacore.com/gps-docs/users_guide/_build/html/mdi.html?highlight=perspectives#perspectives):

> When you leave a perspective, GPS automatically saves its contents (including which windows are opened and their location) so when you return to the same perspective you see the same layout.

I would expect my changes to the Default perspective to be persisted before entering a different perspective.

**Environment:**

```
GPS 2018 (20180528) hosted on x86_64-pc-linux-gnu
GNAT Community 2018 (20180524-73)
```

**Comment by AnthonyLeonardoGracio** [comment] 2018-12-18 13:33
Hello,

We are not able to reproduce the issue on our side with the current development version.

Does it happen only with the OS shell window? Have you tried to reproduce by opening the Python console for instance?

**Comment by AnthonyLeonardoGracio** [comment] 2018-12-18 13:39
Actually we are able to reproduce. We will let you know once it's fixed.

Thanks for reporting!

**Comment by AnthonyLeonardoGracio** [comment] 2019-01-31 09:46
Hello,

This is now fixed in the GPS development version. Thanks for reporting this.

Regards,

**Closed by AnthonyLeonardoGracio** 2019-01-31 09:46 UTC
Labels: bug
