### ISSUE TITLE
Changing comments doesn't mark the document as changed

### ISSUE THREAD

**Issue by embeddedden** [AdaCore/gps#16] opened 2017-06-03 22:20 UTC
Hello, I found out that when I change a comment (GPS 2016 (20160515) hosted on i686-pc-linux-gnu
GNAT GPL 2016 (20160515-49)) the document isn't marked as changed. So, I can change a comment and close the document without any warnings and my changes will be lost.

The way to reproduce: open GPS, create a comment, save the document, continue typing your comment without any white spaces or line breaks, close the file, open it again.

**Comment by AnthonyLeonardoGracio** [comment] 2017-06-08 09:06
Hello, 

We are able to reproduce the issue and not only with comments:  the issue is also present when typing code, saving, and retyping code without clicking on the editor.

We will investigate and fix the issue since it can lead to very annoying problems. Thanks for the report.

**Comment by AnthonyLeonardoGracio** [comment] 2017-06-22 09:54
This is now fixed by efb536e4306d536c

Thanks for opening the issue!

Regards,

**Closed** 2017-06-22 09:55 UTC
Labels: bug
