### ISSUE TITLE
ambiguous expression (cannot resolve "To_LSP_String")

### ISSUE THREAD

**Issue by steve-cs** [AdaCore/gps#97] opened 2020-02-02 21:46 UTC
Appears that one of the recent ada_language_server commits pushed to github in the last 24-48 hours has broken the gps build.

```
2020-02-02T09:40:24.9875515Z gps-lsp_module.adb:1058:22: ambiguous expression (cannot resolve "To_LSP_String")
2020-02-02T09:40:24.9878720Z gps-lsp_module.adb:1058:22: possible interpretation at lsp-types.ads:86
2020-02-02T09:40:24.9881348Z gps-lsp_module.adb:1058:22: possible interpretation at lsp-types.ads:81
2020-02-02T09:40:30.0153710Z 
2020-02-02T09:40:30.0155107Z    compilation of gps-lsp_module.adb failed
```

**Comment by AnthonyLeonardoGracio** [comment] 2020-02-03 09:35
Hello Steve!

This error comes from a patch in the Ada Language Server that was merged on Friday and will hopefully be fixed today.

I am closing this issue since the problem is already known internally. Feel free to build GS again tomorrow ;)

Regards,

**Closed by AnthonyLeonardoGracio** 2020-02-03 09:35 UTC

**Comment by steve-cs** [comment] 2020-02-04 10:07
Yes, that one's fixed and it appears to me that another LSP related even more recent commit  broke it somewhere else.  If you're picking these up internally, I'll stop reporting them.

```
2020-02-04T09:40:50.0832284Z gps-lsp_client-editors.adb:105:07: warning: constant "Server" is not referenced
2020-02-04T09:41:02.8380798Z 
2020-02-04T09:41:02.8381686Z    compilation of gps-lsp_client-editors.adb failed
2020-02-04T09:41:02.8381746Z 
```

**Comment by AnthonyLeonardoGracio** [comment] 2020-02-04 10:20
Hello Steve

> Yes, that one's fixed and it appears to me that another LSP related even more recent commit broke it somewhere else. If you're picking these up internally, I'll stop reporting them.
> 
> ```
> 2020-02-04T09:40:50.0832284Z gps-lsp_client-editors.adb:105:07: warning: constant "Server" is not referenced
> 2020-02-04T09:41:02.8380798Z 
> 2020-02-04T09:41:02.8381686Z    compilation of gps-lsp_client-editors.adb failed
> 2020-02-04T09:41:02.8381746Z 
> ```

Yes, we usually catch them during the day and we fix them ASAP, so no need to report them in general. Thanks nonetheless!
