### ISSUE TITLE
Missing/Dead Links on " Website Download Page"

### ISSUE THREAD

**Issue by sanyaade-teachings** [AdaCore/gps#122] opened 2021-09-26 12:14 UTC
Hi All,

Just wanted to bring to notice that there are issues with links to download binary images on Adacore.com. (dead links)
Please see below:
![image](https://user-images.githubusercontent.com/4993211/134807372-ae57daca-b9e0-4f98-84c1-fcaa58c84869.png)

Same on "More packages, platforms, versions and sources" link:
![image](https://user-images.githubusercontent.com/4993211/134807448-875348b2-e9c0-47f3-aa1f-58999d70718e.png)

I noticed those issues since last Friday but they are still there till now.

May thanks for your support! 

God blesses!!!

Best regards,
Sanyaade

**Comment by Fabien-Chouteau** [comment] 2021-09-27 08:25
Thank you @sanyaade-teachings, we will bring the downloads back up as soon as possible.

We now have an internal ticket open for this, and I am closing the issue here since the problem is not directly related to the project of this repository.

**Closed by Fabien-Chouteau** 2021-09-27 08:25 UTC
